name: algolia_client_abtesting_v3
version: 1.44.0
description: A sub-package of the AlgoliaSearch library, offering abtesting v3-specific functionalities for enhanced search and discovery in Dart/Flutter apps.
homepage: https://www.algolia.com/doc/
repository: https://github.com/algolia/algoliasearch-client-dart/tree/main/packages/client_abtesting_v3
topics:
  - search
  - discovery

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  algolia_client_core: ^1.44.0
  json_annotation: ^4.8.1
  collection: ^1.17.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: '>=6.0.0 <6.9.0'
  lints: ^6.0.0
  logging: ^1.2.0
  test: ^1.25.8